/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package second.gradle;

public class App {
    public String getGreeting() {
        // return "Hello World!2";
        return null;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
